# -*- coding: utf-8 -*-
"""UAS PRAKTEK DIMAS RANDAYU.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xw9g5u_yuYPyyFGAyhf4E0NI1Bi3VjsI
"""

SIZE = 10
hash_table = [None] * SIZE


def hash_function(key):
    return key % 10


def insert(kode, nama, harga):
    index = hash_function(kode)
    awal = index

    while hash_table[index] is not None:
        index = (index + 1) % SIZE
        if index == awal:
            print("Hash Table Penuh!")
            return

    hash_table[index] = {
        "kode": kode,
        "nama": nama,
        "harga": harga
    }


def tampilkan():
    print("\n=== DATA PRODUK ===")
    for i, data in enumerate(hash_table):
        if data is not None:
            print(f"Index {i} : {data['kode']} | {data['nama']} | Rp {data['harga']:,}")
        else:
            print(f"Index {i} : Kosong")


def cari(kode):
    index = hash_function(kode)
    awal = index

    while hash_table[index] is not None:
        if hash_table[index]["kode"] == kode:
            return hash_table[index]
        index = (index + 1) % SIZE
        if index == awal:
            break

    return None


def selection_sort():
    data = []

    for item in hash_table:
        if item is not None:
            data.append(item)

    n = len(data)

    for i in range(n - 1):
        min_idx = i
        for j in range(i + 1, n):
            if data[j]["harga"] < data[min_idx]["harga"]:
                min_idx = j

        data[i], data[min_idx] = data[min_idx], data[i]

    return data

# =====================
# Data Uji
# =====================
insert(101, "Mouse", 120000)
insert(205, "Keyboard", 250000)
insert(118, "Flashdisk", 85000)
insert(310, "Monitor", 1750000)
insert(412, "Printer", 950000)
insert(399, "minyak telon", 1000000000)
insert(812,"earphone ", 1000000)
insert(522, "smartphone", 5000000)
insert(523, "laptop", 800000)
insert(524, "tumbler", 700000)


tampilkan()


kode = int(input("\nMasukkan kode yang dicari: "))
hasil = cari(kode)

if hasil:
    print("\nData Ditemukan")
    print("Kode  :", hasil["kode"])
    print("Nama  :", hasil["nama"])
    print("Harga :", hasil["harga"])
else:
    print("Data tidak ditemukan.")

urut = selection_sort()

print("\n=== DATA SETELAH DIURUTKAN BERDASARKAN HARGA ===")
for p in urut:
    print(f"{p['kode']} | {p['nama']} | Rp {p['harga']:,}")

